add generation of npm clients to openapi modules
boudicca-events/boudicca.events pull request #251
Opened 2024-01-14 19:38 UTC by twatzl

2024-01-21 09:58 UTC, kadhonn commented on boudicca.base/enricher-openapi/build.gradle.kts
> +    outputDir.set(layout.buildDirectory.dir("/generated/java").get().toString())
i think this is interpreted as an absolute path, so remove the first / or try ./generated

2024-01-22 09:41 UTC, Yolgie commented
why did you add the generated code as well?

2024-01-22 10:00 UTC, Yolgie requested changes
looks roughly good, but i would not commit the generated code

- [ ] please remove the generated folders from the MR
- [ ] please add the generated folders to the .gitignore

2024-01-25 17:03 UTC, kadhonn commented
oook, i kinda got carrried away but i really wanted to do a big cleanup of our gradle stuff. to avoid having merge conflicts with tobis changes i just based mine on his, and also did the cleanup of the typescript files... so that is now a big monster of PR with way too many changes, but i really wanted to get this done. you can have a look at the commits, i tried my best to group them nicely.

anyway, what i did was create "convention-plugins" for our project, where we standardize all the build config for different projects.
so now we have one for springboot apps, openapi client generators, openapi spec generators and some base files as well
that is soo much cleaner already, but there are still some things to be done :)

2024-01-25 18:00 UTC, merged

2024-01-25 18:06 UTC, kadhonn commented
i made a mistake, sorry. new MR is #258